spring:
  application:
    name: gateway-service

server:
  port: 8094

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
    register-with-eureka: true
    fetch-registry: true

cloud:
  gateway:
    routes:
      - id: project-service
        uri: lb://PROJECT-SERVICE
        predicates:
          - Path=/api/project/**
        filters:
          - StripPrefix=1

      - id: task-service
        uri: lb://TASK-SERVICE
        predicates:
          - Path=/api/task/**
        filters:
          - StripPrefix=1

      - id: resource-service
        uri: lb://RESOURCE-SERVICE
        predicates:
          - Path=/api/resource/**
        filters:
          - StripPrefix=1

      - id: PersonService
        uri: lb://PersonService
        predicates:
          - Path=/api/auth/**
        filters:
          - StripPrefix=1
